import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { z } from "zod";

export const TelegramPluginConfig = z.object({
  enabled: z.boolean().default(false),
  botToken: z.string().default(""),
  allowedUserIds: z.array(z.number()).default([]),
  allowedChatIds: z.array(z.number()).default([]),
  defaultRepo: z.string().nullable().default(null),
});
export type TelegramPluginConfig = z.infer<typeof TelegramPluginConfig>;

export const DiscordPluginConfig = z.object({
  enabled: z.boolean().default(false),
  botToken: z.string().default(""),
  allowedUserIds: z.array(z.string()).default([]),
  allowedChannelIds: z.array(z.string()).default([]),
  defaultRepo: z.string().nullable().default(null),
});
export type DiscordPluginConfig = z.infer<typeof DiscordPluginConfig>;

/**
 * Default agent instructions appended to every task. Kept conservative so
 * outputs (commit messages, PR bodies, agent prose) don't carry model or
 * vendor self-references — easy to override per install with
 * `agentd settings set agentInstructions "..."`.
 */
export const DEFAULT_AGENT_INSTRUCTIONS = [
  "Do not mention that you are Claude, Codex, an AI, an LLM, or any specific model or vendor in your output.",
  "Do not add 'Co-Authored-By', 'Generated with', '🤖 Generated by', or similar attribution trailers to commit messages, PR descriptions, or any text you produce.",
  "Keep all output focused on the task itself — no meta-commentary about how the work was performed.",
].join(" ");

/**
 * User-provided guidance appended to the helper's prompt when generating
 * commit messages. Empty by default. Example:
 *   "Always lowercase. Don't include scope. Mention affected packages
 *    in the body when more than one is touched."
 */
export const DEFAULT_COMMIT_INSTRUCTIONS = "";

/**
 * User-provided guidance appended to the helper's prompt when generating
 * PR titles + bodies. Empty by default. Example:
 *   "Open with a one-sentence summary, then a `## Changes` heading with
 *    bullets. Skip 'Test plan'. Don't reference issues unless the diff
 *    explicitly mentions them."
 */
export const DEFAULT_PR_INSTRUCTIONS = "";

/**
 * One model the user can pick in any agent picker. The registry lives
 * in `cfg.models` and is fully overridable from `~/.agentd/config.json`
 * — adding a new model is a config edit + daemon restart, no code.
 *
 *   id       — what gets passed to the CLI as `--model`. Must be exact.
 *   label    — short display name shown in pickers.
 *   aliases  — nicknames the AI router accepts ("opus", "opus 4.7").
 *   tier     — optional UI grouping. The deepest tier is shown as the
 *              "max thinking" pair; fast tiers are flagged in the UI.
 */
export const ModelEntry = z.object({
  id: z.string().min(1),
  label: z.string().default(""),
  aliases: z.array(z.string()).default([]),
  tier: z
    .enum(["fast", "balanced", "deep", "deepest"])
    .optional(),
});
export type ModelEntry = z.infer<typeof ModelEntry>;

/**
 * Per-agent model lists. Each entry is fully self-contained (id +
 * label + aliases). The first entry that has `tier === "deepest"` is
 * treated as the default for that agent when no `defaultModel` is set;
 * otherwise the first entry wins.
 */
export const ModelRegistry = z.object({
  claude: z.array(ModelEntry).default([]),
  codex: z.array(ModelEntry).default([]),
});
export type ModelRegistry = z.infer<typeof ModelRegistry>;

export const DEFAULT_MODEL_REGISTRY: ModelRegistry = {
  claude: [
    {
      id: "claude-opus-4-7",
      label: "opus 4.7",
      aliases: ["opus", "claude-opus", "opus 4.7", "opus4.7", "opus-4.7"],
      tier: "deep",
    },
    {
      id: "claude-sonnet-4-6",
      label: "sonnet 4.6",
      aliases: ["sonnet", "claude-sonnet", "sonnet 4.6"],
      tier: "balanced",
    },
    {
      id: "claude-haiku-4-5",
      label: "haiku 4.5",
      aliases: ["haiku", "claude-haiku", "haiku 4.5"],
      tier: "fast",
    },
  ],
  codex: [
    {
      id: "gpt-5-codex",
      label: "gpt-5-codex",
      aliases: ["codex", "gpt5-codex", "gpt-5 codex"],
      tier: "balanced",
    },
    {
      id: "gpt-5",
      label: "gpt-5",
      aliases: ["gpt5", "gpt5.0"],
      tier: "fast",
    },
  ],
};

/**
 * Resolve a free-form model nickname (`"opus"`, `"gpt-5.5"`, the full
 * id) against the registry. Falls back to the literal input when no
 * registry match — that lets the user pass a model id the registry
 * doesn't know about (a brand-new release, a private fine-tune, etc.).
 */
export function resolveModelInRegistry(
  raw: string,
  agent: "claude" | "codex",
  registry: ModelRegistry,
): string {
  const k = raw.trim();
  if (!k) return "";
  const list = registry[agent] ?? [];
  const lower = k.toLowerCase();
  // Exact id match.
  for (const m of list) if (m.id === k) return m.id;
  // Alias / case-insensitive id match.
  for (const m of list) {
    if (m.id.toLowerCase() === lower) return m.id;
    if (m.aliases.some((a) => a.toLowerCase() === lower)) return m.id;
  }
  // Substring match on aliases — last resort, helps "opus 4.7" land
  // on "opus 4.7" entry even when whitespace is weird.
  for (const m of list) {
    if (m.aliases.some((a) => a.toLowerCase().replace(/\s+/g, "") === lower.replace(/\s+/g, ""))) {
      return m.id;
    }
  }
  return k;
}

/**
 * Settings for the small Claude invocations agentd makes outside the main
 * task agent: commit message generation, PR body generation, branch name
 * suggestion. Kept separate from the per-task agent config because these
 * helper calls are short and cheap, so a lighter / faster model is usually
 * the right default.
 */
export const AiHelperConfig = z.object({
  /** CLI binary to invoke; defaults to whatever's first on $PATH. */
  binary: z.string().default("claude"),
  /** Optional `--model` override. Empty string means inherit Claude's default. */
  model: z.string().default(""),
  /**
   * Reasoning effort for helper calls. Defaults to `medium` because the
   * tasks (commit subjects, branch names) are short. Bump to `high` for
   * meatier PR bodies if you want the bullets to read better.
   */
  effort: z.enum(["low", "medium", "high", "max", "xhigh"]).default("medium"),
});
export type AiHelperConfig = z.infer<typeof AiHelperConfig>;

export const DEFAULT_AI_HELPER: AiHelperConfig = AiHelperConfig.parse({});

/**
 * Per-operator "last picked" values for the spawn flow. Stored in
 * config.json (server-side) so opening agentd on a second device
 * restores the same defaults without leaking through localStorage.
 *
 * These are pure UX preferences — they never change runtime behavior
 * by themselves. Each form still applies them on submit, and per-task
 * state lives on the Task row.
 */
export const UserPrefs = z.object({
  lastAgent: z.enum(["claude", "codex"]).default("claude"),
  lastBase: z.string().default("main"),
  lastRepo: z.string().default(""),
  lastProjectId: z.string().default(""),
  lastAutoPush: z.boolean().default(true),
  lastAutoPr: z.boolean().default(false),
  lastPermissionMode: z
    .enum(["bypassPermissions", "acceptEdits", "plan"])
    .default("bypassPermissions"),
  lastThinkingLevel: z
    .enum(["low", "medium", "high", "max", "xhigh"])
    .default("high"),
  lastModelClaude: z.string().default(""),
  lastModelCodex: z.string().default(""),
  /** Workspace setup last picks, flattened from the old agentd.workspaceSetup blob. */
  workspaceMode: z.enum(["worktree", "in_place"]).default("worktree"),
  branchMode: z.enum(["new", "existing"]).default("new"),
  pullLatest: z.boolean().default(false),
  /**
   * Project ids that are expanded in the sidebar tree (tasks visible
   * underneath). Also persisted across devices so opening agentd
   * elsewhere keeps the same shape.
   */
  sidebarExpandedProjects: z.array(z.string()).default([]),
  /** Whether the task detail right-side workspace panel is open. */
  taskWorkspaceOpen: z.boolean().default(true),
  /** Pinned repo paths shown at the top of the repo picker. */
  repoPickerPins: z.array(z.string()).default([]),
});
export type UserPrefs = z.infer<typeof UserPrefs>;
export const DEFAULT_USER_PREFS: UserPrefs = UserPrefs.parse({});

export const AgentdConfig = z.object({
  pluginSessionToken: z.string().nullable().default(null),
  /** Appended to the agent's system prompt for every task. */
  agentInstructions: z.string().default(DEFAULT_AGENT_INSTRUCTIONS),
  /**
   * Free-form guidance added to the AI commit-message generator's prompt.
   * Use it to teach the helper your team's commit style without baking
   * a template prefix into the message.
   */
  commitInstructions: z.string().default(DEFAULT_COMMIT_INSTRUCTIONS),
  /**
   * Free-form guidance added to the AI PR-message generator's prompt.
   * Same idea as commitInstructions but for `gh pr create` titles + bodies.
   */
  prInstructions: z.string().default(DEFAULT_PR_INSTRUCTIONS),
  /**
   * Default model passed to each agent CLI when a task doesn't pin one.
   * Empty string means inherit the CLI's own default. The user can pick
   * any model the underlying CLI accepts (Claude opus/sonnet/haiku tiers,
   * Codex gpt-5 / gpt-5-codex, etc.).
   */
  defaultModel: z
    .object({
      claude: z.string().default(""),
      codex: z.string().default(""),
    })
    .default({ claude: "", codex: "" }),
  /**
   * "Last used" form values for the spawn flow. Server-side so they
   * sync across devices instead of getting trapped in browser
   * localStorage.
   */
  prefs: UserPrefs.default(DEFAULT_USER_PREFS),
  /**
   * Token budget for the system-prompt suffix (agentInstructions + skill
   * bodies + repo doc). Skills get dropped (claude/codex first, then
   * global, local last) when the total estimate exceeds this. Soft cap —
   * the agent's actual context window is bigger.
   */
  maxContextTokens: z.number().int().positive().default(8000),
  /**
   * Model + effort used for AI helpers (commit messages, PR bodies, branch
   * names). Separate from the per-task agent configuration so users can pick
   * a fast cheap model for short helper calls without affecting their main
   * agent runs.
   */
  aiHelpers: AiHelperConfig.default(DEFAULT_AI_HELPER),
  /**
   * Per-agent model registry. Override in `~/.agentd/config.json` to
   * add new releases (e.g. `gpt-5.5`) without touching agentd code.
   * Every UI picker, the AI router's alias resolver, and the CLI's
   * model flag all read from here.
   */
  models: ModelRegistry.default(DEFAULT_MODEL_REGISTRY),
  /**
   * Default thinking level applied when a task is spawned without one.
   *   claude — `xhigh` is Claude's own default; `max` is its deepest tier.
   *   codex  — `high` is the practical default; `xhigh` is its deepest tier.
   *   commit/pr/branch — short helper calls; `medium` keeps them fast.
   * The user can override per-task in the spawn UI; this just controls the
   * initial value of those selectors.
   */
  defaultThinking: z
    .object({
      claude: z.enum(["low", "medium", "high", "max", "xhigh"]).default("xhigh"),
      codex: z.enum(["low", "medium", "high", "max", "xhigh"]).default("high"),
    })
    .default({ claude: "xhigh", codex: "high" }),
  plugins: z
    .object({
      telegram: TelegramPluginConfig.default({
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChatIds: [],
        defaultRepo: null,
      }),
      discord: DiscordPluginConfig.default({
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChannelIds: [],
        defaultRepo: null,
      }),
    })
    .default({
      telegram: {
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChatIds: [],
        defaultRepo: null,
      },
      discord: {
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChannelIds: [],
        defaultRepo: null,
      },
    }),
});
export type AgentdConfig = z.infer<typeof AgentdConfig>;

/**
 * Substitutes {placeholder} tokens in templates (PR body, commit body) using
 * the same `renderTemplate` semantics as task templates: unknown placeholders
 * are left literal so they're visible if the user mistyped one.
 */
export function renderConfigTemplate(
  template: string,
  ctx: Record<string, string>,
): string {
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key: string) =>
    key in ctx ? ctx[key]! : `{${key}}`,
  );
}

export type PluginName = "telegram" | "discord";

export function configPath(rootDir: string): string {
  return `${rootDir}/config.json`;
}

export function loadConfig(rootDir: string): AgentdConfig {
  const path = configPath(rootDir);
  if (!existsSync(path)) return AgentdConfig.parse({});
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(path, "utf8"));
  } catch (e) {
    throw new Error(`config at ${path} is not valid JSON: ${(e as Error).message}`);
  }
  const parsed = AgentdConfig.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `config at ${path} failed validation: ${parsed.error.issues
        .map((i) => `${i.path.join(".")}: ${i.message}`)
        .join("; ")}`,
    );
  }
  return parsed.data;
}

export function saveConfig(rootDir: string, config: AgentdConfig): void {
  const path = configPath(rootDir);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(config, null, 2) + "\n", { mode: 0o600 });
}

export function updateConfig(
  rootDir: string,
  fn: (c: AgentdConfig) => AgentdConfig,
): AgentdConfig {
  const next = fn(loadConfig(rootDir));
  saveConfig(rootDir, next);
  return next;
}
