import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { z } from "zod";

export const TelegramPluginConfig = z.object({
  enabled: z.boolean().default(false),
  botToken: z.string().default(""),
  allowedUserIds: z.array(z.number()).default([]),
  allowedChatIds: z.array(z.number()).default([]),
  defaultRepo: z.string().nullable().default(null),
});
export type TelegramPluginConfig = z.infer<typeof TelegramPluginConfig>;

export const DiscordPluginConfig = z.object({
  enabled: z.boolean().default(false),
  botToken: z.string().default(""),
  allowedUserIds: z.array(z.string()).default([]),
  allowedChannelIds: z.array(z.string()).default([]),
  defaultRepo: z.string().nullable().default(null),
});
export type DiscordPluginConfig = z.infer<typeof DiscordPluginConfig>;

/**
 * Default agent instructions appended to every task. Kept conservative so
 * outputs (commit messages, PR bodies, agent prose) don't carry model or
 * vendor self-references — easy to override per install with
 * `agentd settings set agentInstructions "..."`.
 */
export const DEFAULT_AGENT_INSTRUCTIONS = [
  "Do not mention that you are Claude, Codex, an AI, an LLM, or any specific model or vendor in your output.",
  "Do not add 'Co-Authored-By', 'Generated with', '🤖 Generated by', or similar attribution trailers to commit messages, PR descriptions, or any text you produce.",
  "Keep all output focused on the task itself — no meta-commentary about how the work was performed.",
].join(" ");

export const DEFAULT_PR_BODY_TEMPLATE = "Original prompt:\n\n{prompt}\n";

/**
 * Settings for the small Claude invocations agentd makes outside the main
 * task agent: commit message generation, PR body generation, branch name
 * suggestion. Kept separate from the per-task agent config because these
 * helper calls are short and cheap, so a lighter / faster model is usually
 * the right default.
 */
export const AiHelperConfig = z.object({
  /** CLI binary to invoke; defaults to whatever's first on $PATH. */
  binary: z.string().default("claude"),
  /** Optional `--model` override. Empty string means inherit Claude's default. */
  model: z.string().default(""),
  /**
   * Reasoning effort for helper calls. Defaults to `medium` because the
   * tasks (commit subjects, branch names) are short. Bump to `high` for
   * meatier PR bodies if you want the bullets to read better.
   */
  effort: z.enum(["low", "medium", "high", "max", "xhigh"]).default("medium"),
});
export type AiHelperConfig = z.infer<typeof AiHelperConfig>;

export const DEFAULT_AI_HELPER: AiHelperConfig = AiHelperConfig.parse({});

export const AgentdConfig = z.object({
  pluginSessionToken: z.string().nullable().default(null),
  /** Appended to the agent's system prompt for every task. */
  agentInstructions: z.string().default(DEFAULT_AGENT_INSTRUCTIONS),
  /** Prefix for auto-generated commit message subject lines. */
  commitPrefix: z.string().default("agent: "),
  /** Prefix for auto-PR titles. */
  prTitlePrefix: z.string().default(""),
  /**
   * PR body template. Substitutes {prompt}, {task_id}, {branch}, {title}.
   * Empty string means use the prompt verbatim with no extra framing.
   */
  prBodyTemplate: z.string().default(DEFAULT_PR_BODY_TEMPLATE),
  /**
   * Token budget for the system-prompt suffix (agentInstructions + skill
   * bodies + repo doc). Skills get dropped (claude/codex first, then
   * global, local last) when the total estimate exceeds this. Soft cap —
   * the agent's actual context window is bigger.
   */
  maxContextTokens: z.number().int().positive().default(8000),
  /**
   * Model + effort used for AI helpers (commit messages, PR bodies, branch
   * names). Separate from the per-task agent configuration so users can pick
   * a fast cheap model for short helper calls without affecting their main
   * agent runs.
   */
  aiHelpers: AiHelperConfig.default(DEFAULT_AI_HELPER),
  /**
   * Default thinking level applied when a task is spawned without one.
   *   claude — `xhigh` is Claude's own default; `max` is its deepest tier.
   *   codex  — `high` is the practical default; `xhigh` is its deepest tier.
   *   commit/pr/branch — short helper calls; `medium` keeps them fast.
   * The user can override per-task in the spawn UI; this just controls the
   * initial value of those selectors.
   */
  defaultThinking: z
    .object({
      claude: z.enum(["low", "medium", "high", "max", "xhigh"]).default("xhigh"),
      codex: z.enum(["low", "medium", "high", "max", "xhigh"]).default("high"),
    })
    .default({ claude: "xhigh", codex: "high" }),
  plugins: z
    .object({
      telegram: TelegramPluginConfig.default({
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChatIds: [],
        defaultRepo: null,
      }),
      discord: DiscordPluginConfig.default({
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChannelIds: [],
        defaultRepo: null,
      }),
    })
    .default({
      telegram: {
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChatIds: [],
        defaultRepo: null,
      },
      discord: {
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChannelIds: [],
        defaultRepo: null,
      },
    }),
});
export type AgentdConfig = z.infer<typeof AgentdConfig>;

/**
 * Substitutes {placeholder} tokens in templates (PR body, commit body) using
 * the same `renderTemplate` semantics as task templates: unknown placeholders
 * are left literal so they're visible if the user mistyped one.
 */
export function renderConfigTemplate(
  template: string,
  ctx: Record<string, string>,
): string {
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key: string) =>
    key in ctx ? ctx[key]! : `{${key}}`,
  );
}

export type PluginName = "telegram" | "discord";

export function configPath(rootDir: string): string {
  return `${rootDir}/config.json`;
}

export function loadConfig(rootDir: string): AgentdConfig {
  const path = configPath(rootDir);
  if (!existsSync(path)) return AgentdConfig.parse({});
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(path, "utf8"));
  } catch (e) {
    throw new Error(`config at ${path} is not valid JSON: ${(e as Error).message}`);
  }
  const parsed = AgentdConfig.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `config at ${path} failed validation: ${parsed.error.issues
        .map((i) => `${i.path.join(".")}: ${i.message}`)
        .join("; ")}`,
    );
  }
  return parsed.data;
}

export function saveConfig(rootDir: string, config: AgentdConfig): void {
  const path = configPath(rootDir);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(config, null, 2) + "\n", { mode: 0o600 });
}

export function updateConfig(
  rootDir: string,
  fn: (c: AgentdConfig) => AgentdConfig,
): AgentdConfig {
  const next = fn(loadConfig(rootDir));
  saveConfig(rootDir, next);
  return next;
}
