import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { z } from "zod";

export const TelegramPluginConfig = z.object({
  enabled: z.boolean().default(false),
  botToken: z.string().default(""),
  allowedUserIds: z.array(z.number()).default([]),
  allowedChatIds: z.array(z.number()).default([]),
  defaultRepo: z.string().nullable().default(null),
});
export type TelegramPluginConfig = z.infer<typeof TelegramPluginConfig>;

export const DiscordPluginConfig = z.object({
  enabled: z.boolean().default(false),
  botToken: z.string().default(""),
  allowedUserIds: z.array(z.string()).default([]),
  allowedChannelIds: z.array(z.string()).default([]),
  defaultRepo: z.string().nullable().default(null),
});
export type DiscordPluginConfig = z.infer<typeof DiscordPluginConfig>;

/**
 * Default agent instructions appended to every task. Kept conservative so
 * outputs (commit messages, PR bodies, agent prose) don't carry model or
 * vendor self-references — easy to override per install with
 * `agentd settings set agentInstructions "..."`.
 */
export const DEFAULT_AGENT_INSTRUCTIONS = [
  "Do not mention that you are Claude, Codex, an AI, an LLM, or any specific model or vendor in your output.",
  "Do not add 'Co-Authored-By', 'Generated with', '🤖 Generated by', or similar attribution trailers to commit messages, PR descriptions, or any text you produce.",
  "Keep all output focused on the task itself — no meta-commentary about how the work was performed.",
].join(" ");

export const DEFAULT_PR_BODY_TEMPLATE = "Original prompt:\n\n{prompt}\n";

export const AgentdConfig = z.object({
  pluginSessionToken: z.string().nullable().default(null),
  /** Appended to the agent's system prompt for every task. */
  agentInstructions: z.string().default(DEFAULT_AGENT_INSTRUCTIONS),
  /** Prefix for auto-generated commit message subject lines. */
  commitPrefix: z.string().default("agent: "),
  /** Prefix for auto-PR titles. */
  prTitlePrefix: z.string().default(""),
  /**
   * PR body template. Substitutes {prompt}, {task_id}, {branch}, {title}.
   * Empty string means use the prompt verbatim with no extra framing.
   */
  prBodyTemplate: z.string().default(DEFAULT_PR_BODY_TEMPLATE),
  plugins: z
    .object({
      telegram: TelegramPluginConfig.default({
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChatIds: [],
        defaultRepo: null,
      }),
      discord: DiscordPluginConfig.default({
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChannelIds: [],
        defaultRepo: null,
      }),
    })
    .default({
      telegram: {
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChatIds: [],
        defaultRepo: null,
      },
      discord: {
        enabled: false,
        botToken: "",
        allowedUserIds: [],
        allowedChannelIds: [],
        defaultRepo: null,
      },
    }),
});
export type AgentdConfig = z.infer<typeof AgentdConfig>;

/**
 * Substitutes {placeholder} tokens in templates (PR body, commit body) using
 * the same `renderTemplate` semantics as task templates: unknown placeholders
 * are left literal so they're visible if the user mistyped one.
 */
export function renderConfigTemplate(
  template: string,
  ctx: Record<string, string>,
): string {
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key: string) =>
    key in ctx ? ctx[key]! : `{${key}}`,
  );
}

export type PluginName = "telegram" | "discord";

export function configPath(rootDir: string): string {
  return `${rootDir}/config.json`;
}

export function loadConfig(rootDir: string): AgentdConfig {
  const path = configPath(rootDir);
  if (!existsSync(path)) return AgentdConfig.parse({});
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(path, "utf8"));
  } catch (e) {
    throw new Error(`config at ${path} is not valid JSON: ${(e as Error).message}`);
  }
  const parsed = AgentdConfig.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `config at ${path} failed validation: ${parsed.error.issues
        .map((i) => `${i.path.join(".")}: ${i.message}`)
        .join("; ")}`,
    );
  }
  return parsed.data;
}

export function saveConfig(rootDir: string, config: AgentdConfig): void {
  const path = configPath(rootDir);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(config, null, 2) + "\n", { mode: 0o600 });
}

export function updateConfig(
  rootDir: string,
  fn: (c: AgentdConfig) => AgentdConfig,
): AgentdConfig {
  const next = fn(loadConfig(rootDir));
  saveConfig(rootDir, next);
  return next;
}
